package logic.db.classes;
// Generated 5 may 2026, 12:11:25 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Puntuaciones generated by hbm2java
 */
public class Puntuaciones implements java.io.Serializable {

	private int idPuntuacion;
	private Usuarios usuarios;
	private long puntuacion;
	private Timestamp fecha;
	private String idioma;

	public Puntuaciones() {
	}

	public Puntuaciones(int idPuntuacion, Usuarios usuarios, long puntuacion, Timestamp fecha) {
		this.idPuntuacion = idPuntuacion;
		this.usuarios = usuarios;
		this.puntuacion = puntuacion;
		this.fecha = fecha;
	}

	public Puntuaciones(int idPuntuacion, Usuarios usuarios, long puntuacion, Timestamp fecha, String idioma) {
		this.idPuntuacion = idPuntuacion;
		this.usuarios = usuarios;
		this.puntuacion = puntuacion;
		this.fecha = fecha;
		this.idioma = idioma;
	}

	public int getIdPuntuacion() {
		return this.idPuntuacion;
	}

	public void setIdPuntuacion(int idPuntuacion) {
		this.idPuntuacion = idPuntuacion;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public long getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(long puntuacion) {
		this.puntuacion = puntuacion;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}

	public String getIdioma() {
		return this.idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

}
