package logic.db.classes;
// Generated 5 may 2026, 12:11:25 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private int idUsuario;
	private String nombre;
	private Set puntuacioneses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int idUsuario, String nombre) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
	}

	public Usuarios(int idUsuario, String nombre, Set puntuacioneses) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.puntuacioneses = puntuacioneses;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPuntuacioneses() {
		return this.puntuacioneses;
	}

	public void setPuntuacioneses(Set puntuacioneses) {
		this.puntuacioneses = puntuacioneses;
	}

}
